language: java
jdk:
  - openjdk14
sudo: false
install: true
script: mvn clean package -DskipTests=true
notifications:
  email:
    recipients:
      - esfero1505@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: PQoTW70mHqa8eQ+jMXOhGKm7vXGnVinP9iQs+6ruH0MBs8hj4TbzkVWpXBhM9Muw68fcxCKf9/LNAOQuL3NhAUAFtotiBxD7YkjynFTgmWznzM2EYFlv2b9hCEzphwbHIH486bwePuAFqUYhH4sFWbkxglXC5B6313KWwuEIC7sYQyMqNI7+uwKeNfcjku37q5Z0jIhXNGrl+j15piByFlbRVF5ZW2pKmzAHdjtYdFQs+QercyjFSUkEqugpWPL+r+TtdEQZYLrthseXTrWhxo0E7+pcgXXiJjYjc/6m2HZ+HHqYujKX9ZkYommwhfHi8YF4wdho7wf5ifOGScySt4Acd0ZkhInBEIaerpCDBHqWPMMY2FjyLNMsANXUSWlh4jTCxZbCHynxlIIOCAIxNM2vJyGv2LzXQSHpq0ylV+EchME8okEKMt37tFKM0eyEy8mnio+Kk+cgf4GbL1hI0kvk7aqWzFMuqeQK1tLTV4+J7mJKHxNUdulEtF8wiqpY0pHuNmay/wg+l3jSky51ttjVN/CRWVh6C5weD3WiL2DiJrI8B7jz5/TOnMX6l8+viDCx4/+oYNYDj/Ux/2lbP2SPGCI+aL2a4FS/z79K/k8voLo4dfB2ZFEY7zYLtbUAcD0o7Rx+HWMlCbJDekjtujVLtS8usZktcShtIGqHuHo=
    app: arcane-badlands-51939